accounts/urls.py
from django.conf.urls import url
from accounts import views
from django.contrib.auth.views import login, logout, password_reset, password_reset_done, password_reset_confirm, password_reset_complete
from django.core.urlresolvers import reverse
from django.conf import settings
from django.conf.urls.static import static

# app_name = 'accounts'
urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^login/$', login, {'template_name': 'accounts/login.html'}, name='login'),
    url(r'^logout/$', logout, {'template_name': 'accounts/logged_out.html'}, name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^profile/$', views.view_profile, name='profile'),
    url(r'^profile/edit/$', views.editProfile, name='edit_profile'),
    url(r'^change-password/$', views.change_password, name='change_password'),
    #/account/reset-password/
    url(r'^reset-password/$', password_reset, {'template_name': 'accounts/reset_password.html','email_template_name': 'accounts/reset_password_email.html','post_reset_redirect': 'accounts:password_reset_done'}, name='reset_password'),

    url(r'^reset-password/done/$', password_reset_done, {'template_name': 'accounts/reset_password_done.html'}, name='password_reset_done'),

    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm, {'template_name': 'accounts/reset_password_confirm.html', 'post_reset_redirect' : 'accounts:password_reset_complete'}, name='password_reset_confirm'),
    url(r'^reset-password/complete/$', password_reset_complete, {'template_name': 'accounts/reset_password_complete.html'}, name='password_reset_complete'),

]

apage/urls.py
from django.conf.urls import url
from apage import views

app_name = 'apage'

urlpatterns = [
    #/apage/
    url(r'^$', views.index, name='index'),
    #/apage/quote_id/
    url(r'^(?P<quote_id>[0-9]+)/$', views.detail, name='detail'),
]

home/urls.py
from django.conf.urls import url
from home import views

urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='home'),
]

usrreg/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib import admin
from django.contrib.auth import views as auth_views
from apage import views
from accounts import views
from django.shortcuts import redirect
from django.contrib.auth.views import logout
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.login_redirect, name='login_redirect'),
    url(r'^admin/', admin.site.urls),
    url(r'^apage/', include('apage.urls')),
    url(r'^account/', include('accounts.urls', namespace='accounts')),
    #url(r'^home/', include('home.urls', namespace='home')),
    # url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', auth_views.password_reset_confirm,{'post_reset_redirect': 'password_reset_complete', 'template_name': 'accounts/reset_password_confirm.html'}, name='password_reset_confirm'),
    # url(r'^reset-password/complete/$', auth_views.password_reset_complete, {'template_name': 'accounts/reset_password_complete.html'}, name='password_reset_complete'),
      ]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apage/models.py
from django.db import models
from django.core.urlresolvers import reverse   #to divert them to any page(detail page)after they submit the model form

# Create your models here.
class Quote(models.Model):
    text = models.CharField(max_length=1000, default="Write right on me...Pour your heart")
    tags = models.CharField(max_length=1000, default="Morality")

    def get_absolute_url(self):
        return reverse('apage:detail', kwargs={'pk':self.pk})

    def __str__(self):
        return self.text[0:30] + self.tags

class About_art(models.Model):
    quote = models.ForeignKey(Quote, on_delete=models.CASCADE)
    artist_name = models.CharField(max_length=100, default="Anonumous")
    artist_title = models.CharField(max_length=100, default="The Seeker")
    artist_image = models.CharField(max_length=150)
    artist_des = models.CharField(max_length=1000)
    artist_story = models.CharField(max_length=3000)

    def __str__(self):
        return self.artist_des[0:50]

#
# class User_Profile(models.Model):
#     user_name = models.CharField(max_length=100, default="Anonumous")
#     user_title = models.CharField(max_length=100, default="The Seeker")
#     user_image = models.CharField(max_length=150)
#     user_lct = models.CharField(max_length=600)
#     user_gen = models.CharField(max_length=600)
#     user_age = models.CharField(max_length=600)
#     user_int = models.CharField(max_length=600)
#     user_goal = models.CharField(max_length=600)
#     user_des = models.CharField(max_length=1000)
#     user_quote = models.CharField(max_length=1000)
#
#     def __str__(self):
#         return self.user_name + self.user_title
#
#     def get_absolute_url(self):
#         return reverse('apage:profile', kwargs={'pk': self.pk})

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.db import models
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth.forms import UserChangeForm, UserCreationForm

class RegistrationForm(UserCreationForm):
      email = forms.EmailField(required=True)
      class Meta:
        model = User
        fields=(
            'first_name',
            'last_name',
            'email',
            'username',
            'password1',
            'password2',
        )
      def save(self, commit=True):
          user = super(RegistrationForm, self).save(commit=False)
          user.first_name = self.cleaned_data['first_name']
          user.last_name = self.cleaned_data['first_name']
          user.email = self.cleaned_data['email']
          if commit:
              user.save()
          return user

class EditProfileform(UserChangeForm):
    class Meta:
        model = User
        fields = (
            'email',
            'first_name',
            'last_name',
            'password',
        )

apage/views.py
from .models import Quote
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from django.views import generic
from django.views.generic import CreateView, DeleteView, UpdateView
from .models import Quote


def index(request):
    all_quotes = Quote.objects.all()
    return render(request,'apage/index.html', {'all_quotes': all_quotes})


def detail(request, quote_id):
    quote = get_object_or_404(Quote, pk=quote_id)
    return render(request, 'apage/detail.html', {'quote': quote})


class Index(generic.ListView):
    template_name = 'apage/index.html'
    context_object_name = 'all_quotes'

    def get_queryset(self):
        return Quote.objects.all()

class Detail(generic.DetailView):
    template_name = 'apage/detail.html'
    model = Quote


class QuoteCreate(CreateView):
    model = Quote
    fields = ['text', 'tag']

class QuoteUpdate(UpdateView):
    model = Quote
    fields = ['text', 'tag']

class QuoteDelete(DeleteView):
    model = Quote
    success_url = reverse_lazy('apage:index')

accounts/templates/accounts/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %} <title>Accounts</title> {% endblock %}

    <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <!-- Latest compiled and minified JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <!--loading css file-->
        {% load static %}
        <link type="text/css" rel="stylesheet" href={% static 'accounts/style.css' %}/>
        <title>Base</title>
</head>
<body>
    <div class="container">
      <nav class="navbar navbar-default">
          <div class="container-fluid">
              <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Wall Of Thoughts!</a>
              </div>
              <div id="navbar" class="navbar-collapse collapse">
                {% if user.is_authenticated %}
                <ul class="nav navbar-nav">
                  <li><a href="#">Home</a></li>
                  <li><a href="{% url 'accounts:profile' %}">Profile</a></li>
                  <li><a href="{% url 'accounts:edit_profile' %}">Edit Profile</a></li>
                  <li><a href="{% url 'accounts:change_password' %}">Change Password</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                </ul>
                {% else %}
                <ul class="nav navbar-nav">
                  <li><a href="#">Home</a></li>
                  <li><a href="{% url 'accounts:login' %}">Login</a></li>
                  <li><a href="{% url 'accounts:reset_password' %}">Reset Password</a></li>
                </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="{% url 'accounts:register' %}">Register</a></li>
                    </ul>
                {% endif%}
                  </div>
          </div>
      </nav>
    </div> <!-- /container -->
{% block content %}
    <h1>Base</h1>
{% endblock %}
</body>
</html>

accounts/templates/accounts/change_password.html
{% extends 'accounts/base.html' %}
{% block content %}
    <div class="container">
        <h1>Password Change</h1>
            <form action="" method="post">
                {% csrf_token %}
                {{ form.as_p }}
            <button type="submit">Submit</button>
            </form>
        {% endblock %}
    </div>

accounts/templates/accounts/login.html
{% extends 'accounts/base.html' %}
{% block content %}
    <div class="container">
        <h1>Welcome</h1>
        <p>you can login here!</p>
        <form method="post" action="">
            {{ form.as_p }}
            {% csrf_token %}
            <button type="submit" name="button">Login</button>
        </form>
    </div>
{% endblock %}

accounts/templates/accounts/password_reset_complete.html
{% extends 'base.html' %}

{% block content %}
  <p>
    Your password has been set. You may go ahead and <a href="{% url 'signin' %}">sign in</a> now.
  </p>
{% endblock %}

accounts/templates/accounts/password_reset_confirm.html
{% extends 'apage/base.html' %}

{% block content %}
  {% if validlink %}
    <h3>Change password</h3>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Change password</button>
    </form>
  {% else %}
    <p>
      The password reset link was invalid, possibly because it has already been used.
      Please request a new password reset.
    </p>
  {% endif %}
{% endblock %}

accounts/templates/accounts/password_reset_done.html
{% extends 'apage/base.html' %}

{% block content %}
  <p>
    We've emailed you instructions for setting your password, if an account exists with the email you entered.
    You should receive them shortly.
  </p>
  <p>
    If you don't receive an email, please make sure you've entered the address you registered with,
    and check your spam folder.
  </p>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'accounts/base.html' %}
{% block content %}
    <div class="container">
        <h3>Profile Info</h3>
        <img src="{{ user.userprofile.image.url }}" alt="No Profile Photo" width="200" height="200"/>
        <p>Username: {{ user.username }}</p>
        <p>First Name: {{ user.first_name }}</p>
        <p>Last Name: {{ user.last_name }}</p>
        <p>Title: {{ user.userprofile.title }}</p>
        <p>Age: {{ user.userprofile.age }}</p>
        <p>Contact No: {{ user.userprofile.phone }}</p>
        <p>Reg Email: {{ user.email }}</p>
        <p>Location: {{ user.userprofile.address }}</p>
        <p>Description: {{ user.userprofile.description }}</p>
        <p>Story: {{ user.userprofile.Story }}</p>
        <p>Gender: {{ user.userprofile.gender }}</p>

    </div>
{% endblock %}
    usrreg/media/profile_image/image1.jpg

accounts/templates/accounts/profile_edit.html
{% extends 'accounts/base.html' %}
{% block content %}
    <div class="container">
        <h1>Edit Profile</h1>
            <form action="" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Submit</button>
            </form>
        {% endblock %}
    </div>

accounts/templates/accounts/reg_form.html
{% extends 'accounts/base.html' %}
{% block content %}
    <div class="container">
        <h1>Register</h1>
            <form action="" method="post">
                {% csrf_token %}
                {{ form.as_p }}
            <button type="submit">Submit</button>
            </form>
        {% endblock %}
    </div>

accounts/templates/accounts/reset_password_complete.html
{% extends 'accounts/base.html' %}
{% block content %}
    <div class="container">
        <h1>Password reset complete</h1>
        <form method="get" action="">
            {{ form.as_p }}
        </form>
    <a href="{% url 'accounts:login' %}">Click To Login!</a>
    </div>
{% endblock %}

accounts/templates/accounts/reset_password_confirm.html
{% extends 'accounts/base.html' %}
{% block content %}
    <div class="container">
        <h1>Enter new password</h1>
        <p>Please enter your new password twice so we can verify you typed it in correctly.</p>
        <form method="post" action="">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Change Password</button>
        </form>
    </div>
{% endblock %}

accounts/templates/accounts/reset_password_done.html
{% extends 'accounts/base.html' %}
{% block content %}
    <div class="container">
        <h1>Password reset sent</h1>
        <p>We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.
            If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.</p>
        <form method="get" action="">
            {{ form.as_p }}
        </form>
    </div>
{% endblock %}

accounts/templates/accounts/reset_password_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

accounts/templates/accounts/signup.html
{% extends 'apage/base.html' %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}

apage/templates/apage/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Base</title>
</head>
<body>

{% load staticfiles %}

    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'apage/style.css' %}"/>

    <div class="container">
        <div class="row header-box">
            <div class="col-md-8">
                <h1>
                    <a href="{% url 'apage:index' %}" style="text-decoration: none">Quotes</a>
                </h1>
            </div>
            <div class="col-md-4">
                <p>
                    <a href="#">Register</a>
                    <a href="#">Login</a>
                    <a href="#">Logout</a>
                    <a href="#">My Profile</a>
            <!--<a href="% url 'apage:add_quote' %}">Add Quote</a>-->
                </p>
            </div>
        </div>
    </div>

{% block content %}
{% endblock %}
</body>
</html>

apage/templates/apage/detail.html
{% extends 'apage/base.html' %}
{% block content %}
<div class="container">

<div class="row">
        <div class="col-md-8">
            <div class="quote" itemscope itemtype="#">
        {% for art_profile in quote.about_art_set.all %}
                <img src="https://www.biography.com/.image/c_fit%2Ccs_srgb%2Ch_406%2Cq_50%2Cw_620/MTIwNjA4NjMzODAzNDc0NDQ0/einstein-albert-head-raw.jpg" alt="Artist Image" height="200" width="200"/>
                <h4>{{ art_profile.artist_name }}</h4>
                <h3>{{ art_profile.artist_title }}</h3>
                <p><em>{{ art_profile.artist_des }}</em></p>
                <p>{{ art_profile.artist_story }}</p>
                <span class="text" itemprop="text">{{ quote.text }}</span>
            </div>
        </div>
    </div>
{% endfor %}
{% endblock %}

apage/templates/apage/index.html
{% extends 'apage/base.html' %}
{% block content %}
    <h3>Welcome to WOT </h3>

    {% for quote in all_quotes %}
    <div class="row">
        <div class="col-md-8">
            <div class="quote" itemscope itemtype="#">
                <span class="text" itemprop="text">{{ quote.text }}</span>
                <span>by <small class="author" itemprop="author">{{ quote.artist }}</small>
                <a href="{% url 'apage:detail' quote.id %}">(about)</a>
                </span>
                <a href="#"><span class="glyphicon glyphicon-thumbs-up"></span></a>
            </div>
        </div>
    </div>
    {% endfor %}
{% endblock %}

apage/templates/apage/quote_form.html
{% extends 'apage/base.html' %}
{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">


                        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'apage/form-template.html' %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

home/templates/home/home.html
{% extends 'accounts/base.html' %}
{% block content %}
    <h1>I am in Home</h1>
{% endblock %}